name: GitHub Issue LINE Reminder

# on:
#   schedule:
#     # 08:00 Thailand
#     - cron: "0 1 * * *"

#     # 12:00 Thailand
#     - cron: "0 5 * * *"
on:
  schedule:
    # ทุก 5 นาที
    - cron: "*/5 * * * *"

  workflow_dispatch:

permissions:
  issues: read

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get open reminder issues
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh issue list \
            --repo "${{ github.repository }}" \
            --state open \
            --label reminder \
            --json number,title,url \
            > issues.json

          cat issues.json

      - name: Send LINE notification
        env:
          LINE_CHANNEL_ACCESS_TOKEN: 98a39e9ab7ba6822bd3a955a2c3f146f
          LINE_TO: C7b97c98438b6f15ee64ca43c587a90c1
        run: |
          python3 SiamSmileSQLClaimPayBack/scripts/line_reminder.py
